rapidofuriosos:
  driver: postgresql
  port: 5432
  user: postgres
  db: rapidofuriosos
  password: root
  host: localhost

bodega:
  driver: postgresql
  port: 19631
  user: avnadmin
  db: defaultdb
  password: AVNS_bioEowem03jhWeZ2biq
  host: etluv-etluv.k.aivencloud.com