rapidofuriosos:
  driver: postgresql
  port: 5432
  user: postgres
  db: rapidofuriosos
  password: root
  host: localhost

bodega:
  driver: postgresql
  port: 5432
  user: adminbodega
  db: bodegaproyecto
  password: Goddess9039#
  host: bodega.postgres.database.azure.com